# binary_sensor
- platform: template
  sensors:

    movement_upstairs:
      value_template: "{{ states.switch.motionsensor.state == 'on' or states.switch.motionsensor2.state == 'on' or states.binary_sensor.livingroom_sensor_10_0.state == 'on' }}"
      device_class: motion
    movement_stair1:
      value_template: "{{ states.switch.motionsensor.state == 'on' }}"
      device_class: motion
    movement_stair2:
      value_template: "{{ states.switch.motionsensor2.state == 'on' }}"
      device_class: motion
    movement_hall:
      value_template: "{{ states.binary_sensor.hall_sensor_6_0.state == 'on' }}"
      device_class: motion
    movement_livingroom:
      value_template: "{{ states.binary_sensor.livingroom_sensor_10_0.state == 'on' }}"
      device_class: motion
    movement_basement:
      value_template: "{{ states.binary_sensor.basement_sensor_7_0.state == 'on' }}"
      device_class: motion
    movement_porch:
      value_template: "{{ states.sensor.motion_porch.state == 'on' }}"
      device_class: motion

    movement:
      value_template: "{{ states.binary_sensor.movement_stair1.state == 'on' or states.binary_sensor.movement_stair2.state == 'on' or states.binary_sensor.movement_hall.state == 'on' or states.binary_sensor.movement_livingroom.state == 'on' or states.binary_sensor.movement_basement.state == 'on' }}"
      device_class: motion

    door_main:
      value_template: "{{ states.switch.maindoor.state == 'on' }}"
      device_class: opening
    door_back:
      value_template: "{{ states.switch.backdoor.state == 'on' }}"
      device_class: opening
    door_ebalcony:
      value_template: "{{ states.binary_sensor.eastbalcony_sensor_11_0.state == 'on' }}"
      device_class: opening
    door_wbalcony:
      value_template: "{{ states.binary_sensor.westbalcony_sensor_12_0.state == 'on' }}"
      device_class: opening

    doors:
      value_template: "{{ states.binary_sensor.door_main.state == 'on' or states.binary_sensor.door_back.state == 'on' or states.binary_sensor.door_ebalcony.state == 'on' or states.binary_sensor.door_wbalcony.state == 'on' }}"
      device_class: opening

    sleeping:
      value_template: "{{ states.input_boolean.sleeping.state == 'on' }}"

    awake:
      value_template: "{{ states.input_boolean.sleeping.state == 'off' }}"

    washmachine:
      value_template: "{{ states.sensor.washmachine_power_8_4.state | int > 2 }}"


- platform: aurora
