# binary_sensor
- platform: template
  sensors:

    movement_upstairs:
      value_template: "{{ states.switch.motionsensor.state == 'on' or states.switch.motionsensor2.state == 'on' or states.binary_sensor.livingroom_sensor.state == 'on' or states.sensor.motion_kitchen.state == 'detected' }}"
      device_class: motion
    movement_downstairs:
      value_template: "{{ states.binary_sensor.hall2_sensor.state == 'on' or states.binary_sensor.hall_sensor.state == 'on' or states.sensor.motion_kids.state == 'detected' }}"
      device_class: motion
    movement_stair1:
      value_template: "{{ states.switch.motionsensor.state == 'on' }}"
      device_class: motion
    movement_stair2:
      value_template: "{{ states.switch.motionsensor2.state == 'on' }}"
      device_class: motion
    movement_hall:
      value_template: "{{ states.binary_sensor.hall_sensor.state == 'on' }}"
      device_class: motion
    movement_hall2:
      value_template: "{{ states.binary_sensor.hall2_sensor.state == 'on' }}"
      device_class: motion
    movement_livingroom:
      value_template: "{{ states.binary_sensor.livingroom_sensor.state == 'on' }}"
      device_class: motion
    movement_basement:
      value_template: "{{ states.binary_sensor.basement_sensor.state == 'on' }}"
      device_class: motion
    movement_porch:
      value_template: "{{ states.sensor.motion_porch.state == 'detected' }}"
      device_class: motion

    movement:
      value_template: "{{ states.binary_sensor.movement_upstairs.state == 'on' or states.binary_sensor.movement_downstairs.state == 'on' }}"
      #value_template: "{{ states.switch.motionsensor.state == 'on' or states.switch.motionsensor2.state == 'on' or states.binary_sensor.livingroom_sensor.state == 'on' or states.binary_sensor.hall2_sensor.state == 'on' or states.binary_sensor.hall_sensor.state == 'on' }}"
      device_class: motion

    door_main:
      value_template: "{{ states.switch.maindoor.state == 'on' }}"
      device_class: opening
    door_back:
      value_template: "{{ states.switch.backdoor.state == 'on' }}"
      device_class: opening
    door_ebalcony:
      value_template: "{{ states.binary_sensor.eastbalcony_sensor.state == 'on' }}"
      device_class: opening
    door_wbalcony:
      value_template: "{{ states.binary_sensor.westbalcony_sensor.state == 'on' }}"
      device_class: opening

    doors:
      value_template: "{{ states.binary_sensor.door_main.state == 'on' or states.binary_sensor.door_back.state == 'on' or states.binary_sensor.door_ebalcony.state == 'on' or states.binary_sensor.door_wbalcony.state == 'on' }}"
      device_class: opening

    sleeping:
      value_template: "{{ states.input_boolean.sleeping.state == 'on' }}"

    awake:
      value_template: "{{ states.input_boolean.sleeping.state == 'off' }}"

    washmachine:
      value_template: "{{ states.sensor.washmachine_power.state | int > 2 }}"

    people_home:
      entity_id:
        - device_tracker.vyhbzwsp_paula
        - device_tracker.vyhbzwsp_thomas
        - device_tracker.noahsiniphone
        - device_tracker.kyloren
      delay_off:
        minutes: 5
      value_template: >-
        {{ is_state('device_tracker.vyhbzwsp_paula', 'home')
           or is_state('device_tracker.vyhbzwsp_thomas', 'home')
           or is_state('device_tracker.noahsiniphone', 'home')
           or is_state('device_tracker.kyloren', 'home')
           or is_state('binary_sensor.movement', 'on') }}

- platform: aurora
