# Ethans Room
- platform: mjpeg
  mjpeg_url: http://192.168.1.60/mjpeg.cgi
  name: Ethan
  username: admin
  password: !secret camera_password
  authentication: basic

# Porch
- platform: generic
  still_image_url: !secret porch_camera_url
  name: Porch
  username: admin
  password: !secret camera_password
  authentication: basic

# Livingroom
- platform: mjpeg
  mjpeg_url: http://192.168.1.62/mjpeg.cgi
  name: Livingroom
  username: admin
  password: !secret camera_password
  authentication: basic

# Bedroom
- platform: mjpeg
  mjpeg_url: http://192.168.1.63/mjpeg.cgi
  name: Bedroom
  username: admin
  password: !secret camera_password
  authentication: basic

# Test
#- platform: ffmpeg
#  input: rtsp://admin:*password*@192.168.1.64:554/h264_hd.sdp
#  name: Test
