# Guestroom
- platform: generic_thermostat
  name: Ethan
  heater: switch.heatethan
  target_sensor: sensor.ethan_temperature
  min_temp: 18
  max_temp: 24
  target_temp: 23
  min_cycle_duration:
     minutes: 5
