####################################################
#                                                  #
#                  Basic Settings                  #
#                                                  #
####################################################

###  Global configuration  ###
homeassistant:
  name: Ovre Ringveg 10
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 70
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customized.yaml

###  Zones  ###
zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 200
  icon: mdi:home-variant
  track_ios: true

zone 2:
  name: Work
  latitude: 64.010773
  longitude: 11.488477
  radius: 200
  icon: mdi:city
  track_ios: true

zone 3:
  name: Campus
  latitude: 64.020935
  longitude: 11.509432
  radius: 200
  icon: mdi:school
  track_ios: true

zone 4:
  name: Bestemor
  latitude: 64.005122
  longitude: 11.506884
  radius: 150
  icon: mdi:home
  track_ios: true

#zone 5:
#  name: Tulcea
#  latitude: 45.181967
#  longitude: 28.788152
#  radius: 20000
#  icon: mdi:earth

#zone 6:
#  name: Vegas
#  latitude: 36.108407
#  longitude: -115.172958
#  radius: 20000
#  icon: mdi:dice-6

## Tellstick ##
tellstick:
  signal_repetitions: 2

##  MQTT  ###
mqtt:
  #broker: m20.cloudmqtt.com
  #port: 22527
  #username: !secret mqtt_username
  #password: !secret mqtt_password
  #client_id: Home Assistant
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret local_mqtt_username
  password: !secret local_mqtt_password
  protocol: 3.1
  #tls_insecure: True
  #tls_version: 1.2

##  HTTP  ###
http:
  api_password: !secret http_api_password
  base_url: !secret http_url
  #cors_allowed_origins:
  #  - https://google.com
  #  - https://home-assistant.io
  #use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - 172.16.1.0/24
  #ip_ban_enabled: True
  #login_attempts_threshold: 3

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

###  Directories ###
scene: !include_dir_merge_list scenes/
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensors/

###  Files ###
notify: !include notification.yaml
logger: !include logger.yaml
device_tracker: !include device_trackers.yaml
switch: !include switches.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
group: !include groups.yaml
script: !include scripts.yaml
camera: !include camera.yaml
climate: !include climate.yaml
binary_sensor: !include binary_sensor.yaml
image_processing: !include image_processing.yaml

### Config and maps###
config:
map:

### Input booleans ###
input_boolean: !include input_boolean.yaml

### Input numbers
input_number:
  alarm_clock_hour:
    name: Hour
    icon: mdi:timer
    initial: 5
    min: 0
    max: 23
    step: 1
  alarm_clock_minute:
    name: Minute
    icon: mdi:timer
    initial: 0
    min: 0
    max: 55
    step: 5
  alarm_clock_fade_in_minutes:
    name: Fade In (Minutes)
    icon: mdi:gradient
    initial: 15
    min: 0
    max: 60
    step: 5


####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

### Hue emulation ###
emulated_hue:
  #type: alexa
  host_ip: 192.168.1.90
  listen_port: 8300
  exposed_domains:
    - light
    - switch
    - input_boolean
    - scene
    - script

###  Sun  ###
sun:

###  Logbook  ###
logbook:

# Recorder qith MySQL
recorder:
  db_url: !secret mysql_url
  purge_interval: 7
  purge_keep_days: 28

###  History  ###
history:
  include:
    domains:
      - sensor
      - switch

###  Frontend  ###
frontend:
  themes:
    darkred:
    # Main colors that can be changed
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b" 
    # Colors based on variables, see above
      paper-card-header-color: "var(--paper-item-icon-color)" 
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"


# Discover some devices automatically
discovery:

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend
conversation:

# Custom iframe panels
panel_iframe:
  icinga2:
    title: 'Icinga2'
    icon: 'mdi:chart-line'
    url: 'http://192.168.1.90:8008/icingaweb2/'
  router:
    title: 'EdgeRouter'
    icon: 'mdi:router-wireless'
    url: 'https://192.168.1.1'

# TTS
tts:
  - platform: google

# IOS
ios:

# Telegram bot (for some reason)
telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id

# Zwave
zwave:
  usb_path: /dev/ttyACM0
  config_path: /root/open-zwave/config
  network_key: !secret zwave_key

# Netatmo
netatmo:
  api_key: !secret netatmo_client_id
  secret_key: !secret netatmo_client_secret
  username: !secret netatmo_username
  password: !secret netatmo_password

# Graphs
history_graph:
  group01:
    name: Outside Temperature
    entities:
      - sensor.netatmo_outdoor_temperature
    hours_to_show: 48
    refresh: 600
  group02:
    name: Movement
    entities:
      - binary_sensor.movement_stair1
      - binary_sensor.movement_stair2
      - binary_sensor.movement_hall
      - binary_sensor.movement_hall2
      - binary_sensor.movement_wic
      - binary_sensor.movement_livingroom
      - binary_sensor.movement_porch
      - binary_sensor.movement_kitchen
      - binary_sensor.movement_diningroom
      - binary_sensor.movement_ethan
      - binary_sensor.movement_gym
      - binary_sensor.movement_kids
    hours_to_show: 24
    refresh: 60
