# Device tracker
#  qos: 0
#  devices:
#    Thomas: /location/Thomas
#    Paula: /location/Paula

- platform: nmap_tracker
  hosts: 192.168.1.100-199
  #home_interval: 10
  interval_seconds: 30
  consider_home: 1800
  track_new_devices: no

#- platform: owntracks

- platform: unifi
  host: 192.168.1.90
  port: 8443
  verify_ssl: False
  username: !secret unifi_username
  password: !secret unifi_password
