# Tellstick light
- platform: tellstick

- platform: mqtt_json  
  name: "SN1 LED"  
  state_topic: "bruh/sensornode1"  
  command_topic: "bruh/sensornode1/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0  

