#- platform: mqtt  
#  state_topic: "bruh/sensornode1"  
#  name: "SN1 PIR"  
#  value_template: '{{ value_json.motion }}'  

- platform: mqtt
  state_topic: "homeassistant/porch/motion_sensor"
  name: "Motion Porch"
#  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "homeassistant/kids/motion_sensor"
  name: "Motion Kids"

- platform: mqtt
  state_topic: "homeassistant/kitchen/motion_sensor"
  name: "Motion Kitchen"

- platform: mqtt
  state_topic: "homeassistant/diningroom/motion_sensor"
  name: "Motion Diningroom"

- platform: mqtt
  state_topic: "homeassistant/ethan/motion_sensor"
  name: "Motion Ethan"
