- platform: template
  sensors:

    alarm_clock_time:
      friendly_name: 'Alarm Time'
      icon_template: 'mdi:alarm'
      value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.alarm_clock_hour.state | int, states.input_number.alarm_clock_minute.state | int ) }}'

    alarm_clock_fade_in_minutes:
      friendly_name: 'Fade In (Minutes)'
      icon_template: 'mdi:gradient'
      value_template: '{{ states.input_number.alarm_clock_fade_in_minutes.state | int }}'

    last_movement_upstairs:
      value_template: '{{ as_timestamp(states.binary_sensor.movement_upstairs.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Last Movement Upstairs
      icon_template: mdi:walk

    last_movement_downstairs:
      value_template: '{{ as_timestamp(states.binary_sensor.movement_downstairs.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Last Movement Downstairs
      icon_template: mdi:walk

    last_movement_basement:
      value_template: '{{ as_timestamp(states.binary_sensor.movement_basement.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Last Movement Basement
      icon_template: mdi:walk

    last_movement:
      value_template: '{{ as_timestamp(states.binary_sensor.movement.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Last Movement Inside
      icon_template: mdi:walk

    last_door_main:
      value_template: '{{ as_timestamp(states.binary_sensor.door_main.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Main Door Last Open
      icon_template: mdi:door

    last_door_back:
      value_template: '{{ as_timestamp(states.binary_sensor.door_back.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Back Door Last Open
      icon_template: mdi:door

    last_door:
      value_template: '{{ as_timestamp(states.binary_sensor.door.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
      friendly_name: Any Door Last Open
      icon_template: mdi:door

    house_asleep_timestamp:
      value_template: '{{ as_timestamp(states.input_boolean.house_asleep.last_changed) | timestamp_custom("%H:%M") }}'
      friendly_name: House Fell Asleep
      icon_template: mdi:sleep

    house_awake_timestamp:
      value_template: '{{ as_timestamp(states.input_boolean.house_awake.last_changed) | timestamp_custom("%H:%M") }}'
      friendly_name: House Awoke
      icon_template: mdi:sleep-off

    livingroom_battery:
      value_template: '{{ states.zwave.livingroom.attributes["battery_level"] }}'
      friendly_name: Livingroom Sensor Battery
      icon_template: >-
         {% if states.zwave.livingroom.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.livingroom.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.livingroom.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.livingroom.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.livingroom.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.livingroom.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.livingroom.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.livingroom.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.livingroom.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    basement_battery:
      value_template: '{{ states.zwave.basement.attributes["battery_level"] }}'
      friendly_name: WIC Sensor Battery
      icon_template: >-
         {% if states.zwave.basement.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.basement.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.basement.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.basement.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.basement.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.basement.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.basement.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.basement.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.basement.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    ebalcony_battery:
      value_template: '{{ states.zwave.eastbalcony.attributes["battery_level"] }}'
      friendly_name: E Balcony Sensor Battery
      icon_template: >-
         {% if states.zwave.eastbalcony.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.eastbalcony.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    hall_battery:
      value_template: '{{ states.zwave.hall.attributes["battery_level"] }}'
      friendly_name: Main Hall Sensor Battery
      icon_template: >-
         {% if states.zwave.hall.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.hall.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.hall.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.hall.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.hall.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.hall.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.hall.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.hall.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.hall.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    hall2_battery:
      value_template: '{{ states.zwave.hall2.attributes["battery_level"] }}'
      friendly_name: Inner Hall Sensor Battery
      icon_template: >-
         {% if states.zwave.hall2.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.hall2.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.hall2.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.hall2.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.hall2.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.hall2.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.hall2.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.hall2.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.hall2.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    wbalcony_battery:
      value_template: '{{ states.zwave.westbalcony.attributes["battery_level"] }}'
      friendly_name: W Balcony Sensor Battery
      icon_template: >-
         {% if states.zwave.westbalcony.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.westbalcony.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    thomas_iphone_battery:
      value_template: '{{ states.device_tracker.thomasiphone.attributes["battery"] }}'
      friendly_name: Thomas iPhone Battery
      icon_template: >-
         {% if states.device_tracker.thomasiphone.attributes["battery"] > 90 %}mdi:battery
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 80 %}mdi:battery-90
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 70 %}mdi:battery-80
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 60 %}mdi:battery-70
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 50 %}mdi:battery-60
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 40 %}mdi:battery-50
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 30 %}mdi:battery-40
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 20 %}mdi:battery-30
         {% elif states.device_tracker.thomasiphone.attributes["battery"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    paula_iphone_battery:
      value_template: '{{ states.device_tracker.paulaiphone.attributes["battery"] }}'
      friendly_name: Paula iPhone Battery
      icon_template: >-
         {% if states.device_tracker.paulaiphone.attributes["battery"] > 90 %}mdi:battery
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 80 %}mdi:battery-90
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 70 %}mdi:battery-80
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 60 %}mdi:battery-70
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 50 %}mdi:battery-60
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 40 %}mdi:battery-50
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 30 %}mdi:battery-40
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 20 %}mdi:battery-30
         {% elif states.device_tracker.paulaiphone.attributes["battery"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}

#    low_battery:
#      friendly_name: "Low Battery"
#      value_template: >
#        {%- set threshold = 40 -%}
#        {%- set domains = ['light', 'switch', 'sensor', 'zwave', 'lock'] -%}
#        {%- for domain in domains -%}
#        {%- for item in states[domain] if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown"))) -%}
#            {{ item.attributes.friendly_name }}{%- if not loop.last %}, {% endif -%}
#        {%- endfor -%}
#        {%- endfor -%}
