- platform: template
  sensors:

    movement_upstairs:
      value_template: >-
        {%- if is_state("switch.motionsensor", "off") and is_state("switch.motionsensor2", "off") -%}
          none
        {%- elif is_state("switch.motionsensor", "on") or is_state("switch.motionsensor2", "on") -%}
          motion
        {%- else -%}
          unknown
        {%- endif -%}

    last_movement_upstairs:
      value_template: '{{ as_timestamp(states.sensor.movement_upstairs.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'

    main_door:
      value_template: >-
        {%- if is_state("switch.maindoor", "off") -%}
          closed
        {%- elif is_state("switch.maindoor", "on") -%}
          open
        {%- else -%}
          unknown
        {%- endif -%}

    last_main_door:
      value_template: '{{ as_timestamp(states.sensor.main_door.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'

    # {{ (as_timestamp(now()) - as_timestamp(states.sensor.inngangsdor.last_changed)) }}
    # {{ (as_timestamp(trigger.to_state.last_changed) - as_timestamp(trigger.from_state.last_changed)) }}

    #  value_template: '{{ as_timestamp(states.sensor.main_door.attributes.last_triggered)  | timestamp_custom("%H:%M") }}'

    back_door:
      value_template: >-
        {%- if is_state("switch.backdoor", "off") -%}
          closed
        {%- elif is_state("switch.backdoor", "on") -%}
          open
        {%- else -%}
          unknown
        {%- endif -%}

    last_back_door:
      value_template: '{{ as_timestamp(states.sensor.back_door.last_changed) | timestamp_custom("%a %d %b %H:%M") }}'
    #  value_template: '{{ as_timestamp(states.sensor.back_door.attributes.last_triggered)  | timestamp_custom("%H:%M") }}'

#    last_sleeping:
#      value_template: '{{ as_timastamp(states.binary_sensor.sleeping.state == 'on') | timestamp_custom("%a %H:%M") }}'
#    last_awake:
#      value_template: '{{ as_timastamp(states.binary_sensor.sleeping.state == 'on') | timestamp_custom("%a %H:%M") }}'

    house_asleep_timestamp:
      value_template: '{{ as_timestamp(states.input_boolean.house_asleep.last_changed) | timestamp_custom("%H:%M") }}'
    house_awake_timestamp:
      value_template: '{{ as_timestamp(states.input_boolean.house_awake.last_changed) | timestamp_custom("%H:%M") }}'

    livingroom_battery:
      value_template: '{{ states.zwave.livingroom_10.attributes["battery_level"] }}'
      icon_template: >-
         {% if states.zwave.livingroom_10.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.livingroom_10.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    basement_battery:
      value_template: '{{ states.zwave.basement_7.attributes["battery_level"] }}'
      icon_template: >-
         {% if states.zwave.basement_7.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.basement_7.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.basement_7.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.basement_7.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.basement_7.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.basement_7.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.basement_7.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.basement_7.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.basement_7.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    ebalcony_battery:
      value_template: '{{ states.zwave.eastbalcony_11.attributes["battery_level"] }}'
      icon_template: >-
         {% if states.zwave.eastbalcony_11.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.eastbalcony_11.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    hall_battery:
      value_template: '{{ states.zwave.hall_6.attributes["battery_level"] }}'
      icon_template: >-
         {% if states.zwave.hall_6.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.hall_6.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.hall_6.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.hall_6.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.hall_6.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.hall_6.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.hall_6.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.hall_6.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.hall_6.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    wbalcony_battery:
      value_template: '{{ states.zwave.westbalcony_12.attributes["battery_level"] }}'
      icon_template: >-
         {% if states.zwave.westbalcony_12.attributes["battery_level"] > 90 %}mdi:battery
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 80 %}mdi:battery-90
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 70 %}mdi:battery-80
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 60 %}mdi:battery-70
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 50 %}mdi:battery-60
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 40 %}mdi:battery-50
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 30 %}mdi:battery-40
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 20 %}mdi:battery-30
         {% elif states.zwave.westbalcony_12.attributes["battery_level"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    thomas_iphone_battery:
      value_template: '{{ states.device_tracker.vyhbzwsp_thomas.attributes["battery"] }}'
      icon_template: >-
         {% if states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 90 %}mdi:battery
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 80 %}mdi:battery-90
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 70 %}mdi:battery-80
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 60 %}mdi:battery-70
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 50 %}mdi:battery-60
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 40 %}mdi:battery-50
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 30 %}mdi:battery-40
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 20 %}mdi:battery-30
         {% elif states.device_tracker.vyhbzwsp_thomas.attributes["battery"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
    paula_iphone_battery:
      value_template: '{{ states.device_tracker.vyhbzwsp_paula.attributes["battery"] }}'
      icon_template: >-
         {% if states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 90 %}mdi:battery
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 80 %}mdi:battery-90
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 70 %}mdi:battery-80
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 60 %}mdi:battery-70
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 50 %}mdi:battery-60
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 40 %}mdi:battery-50
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 30 %}mdi:battery-40
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 20 %}mdi:battery-30
         {% elif states.device_tracker.vyhbzwsp_paula.attributes["battery"] > 10 %}mdi:battery-20
         {% else %}mdi:mdi:battery-10
         {% endif %}
