## TEST
#- alias: 'Play sounds on SONOS'
#  trigger:
#    platform: state
#    entity_id: light.officedesk
#    from: 'on'
#  action:
#    - service: media_player.volume_set
#      data:
#        entity_id: media_player.living_room
#        volume_level: 0.25
#    - service: media_player.play_media
#      data:
#        entity_id: media_player.living_room
#        media_content_id: http://192.168.1.90/buss.mp3
#        media_content_type: audio/mp3


#input_boolean.alarm_home


# input_boolean.alarm_away
# Triggering on all movement and doors/windows
- alias: 'Alarm away'
  trigger:
    - platform: state
      entity_id: binary_sensor.movement
      to: 'on'
    - platform: state
      entity_id: binary_sensor.doors
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.alarm_away
      state: 'on'
    - condition: state
      entity_id: input_boolean.alarm_triggered
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id:  input_boolean.alarm_triggered    
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room
        volume_level: 0.75
    - service: media_player.play_media
      data:
        entity_id: media_player.living_room
        media_content_id: http://localhost/sounds/beep.mp3
        media_content_type: audio/mp3
    - service: notify.pushbullet
      data:
        message: 'The alarm (away) has been activated. Waiting 30 seconds.'
    - delay: 00:00:30
    - condition: state
      entity_id: input_boolean.alarm_away
      state: 'on'
    - service: media_player.play_media
      data:
        entity_id: media_player.living_room
        media_content_id: http://localhost/sounds/siren.mp3
        media_content_type: audio/mp3
    - service: notify.pushbullet
      data:
        message: 'The alarm (away) has been fired!'

