######################################################
# Morning lights
######################################################

- alias: 'Good morning'
  trigger:
    platform: state
    entity_id: binary_sensor.movement_upstairs
    state: 'on'
  condition:
    - condition: time
      after: '05:00:01'
      before: '12:00:00'
    - condition: sun
      before: sunrise
      before_offset: "+01:00:00"
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
  action:
    - service: 'scene.turn_on'
      entity_id: 'scene.lights'
    - service: homeassistant.turn_off
      entity_id: 'input_boolean.sleeping'
    - delay: 00:00:02
    - service: homeassistant.turn_off
      entity_id: 'input_boolean.house_awake'
    - delay: 00:00:02
    - service: homeassistant.turn_on
      entity_id: 'input_boolean.house_awake'


#######################################################
# Coming home
#######################################################

- alias: 'Turn on lights when coming home after sunset'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '15:00:00'
      before: '23:59:00'
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
    - condition: state
      entity_id: group.lights_livingroom
      state: 'off'
  action:
    service: 'scene.turn_on'
    entity_id: 'scene.lights'

