#####################################################
# Adjust guestroom climate UP in the afternoon
#####################################################

- alias: 'Adjust guestroom climate for afternoon'
  trigger:
    - platform: time
      after: '17:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
  action:
    service: 'climate.set_temperature'
    entity_id: 'climate.guestroom'
    data:
      temperature: 23.0

#####################################################
# Adjust guestroom climate DOWN in the morning  
#####################################################

- alias: 'Adjust guestroom climate for morning'
  trigger:
    - platform: time
      after: '08:00:00'
  action:
    service: 'climate.set_temperature'
    entity_id: 'climate.guestroom'
    data:
      temperature: 21.0

#####################################################
# Check guestroom heat - NOT above 24 or below 22.5
#####################################################

- alias: 'Check guestroom night - too hot'
  trigger:
    - platform: numeric_state
      entity_id: sensor.guestroom_temperature
      above: 24
  condition:
    - condition: time
      before: '08:00:00'
      after: '17:30:00'
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
  action:
    - service: 'switch.turn_on'
      entity_id: 'switch.heatguestroom'
    - delay: 00:00:03
    - service: 'switch.turn_off'
      entity_id: 'switch.heatguestroom'

- alias: 'Check guestroom night - too cold'
  trigger:
    - platform: numeric_state
      entity_id: sensor.guestroom_temperature
      below: 22
  condition:
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
    - condition: time
      before: '08:00:00'
      after: '17:30:00'
  action:
    - service: 'switch.turn_off'
      entity_id: 'switch.heatguestroom'
    - delay: 00:00:03
    - service: 'switch.turn_on'
      entity_id: 'switch.heatguestroom'



#sensor.guestroom_temperature


