- alias: IP Changed
  trigger:
    - platform: state
      entity_id: sensor.external_ip
  action:
    - service: script.telegram
      data_template:
        message: "External IP changed to {{ states.sensor.external_ip.state }}"
