- alias: 'Good morning'
  trigger:
    platform: state
    entity_id: binary_sensor.movement_upstairs
    state: 'on'
  condition:
    - condition: time
      after: '05:00:01'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id:  input_boolean.house_awake
    - service: homeassistant.turn_off
      entity_id:  input_boolean.sleeping

#    - service: media_player.volume_set
#      data:
#        entity_id: media_player.living_room
#        volume_level: 0.25
#    - service: media_player.play_media
#      data:
#        entity_id: media_player.living_room
#        media_content_id: http://192.168.1.90/sounds/morning.mp3
#       media_content_type: audio/mp3
#    - service: homeassistant.turn_on
#      entity_id: script.home_status

