###########################################
# Kodi playing
###########################################

- alias: 'Kodi playing'
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  action:
    service: 'light.turn_off'
    entity_id: 'light.star'

###########################################
# Kodi not playing any more
# * After sunset
# * Not sleeping
###########################################

- alias: 'Kodi not playing'
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'playing'
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: 'light.turn_on'
    entity_id: 'light.star'

