#############################################################
# Sunrise +1 hour
# Conditions:
# * Lights on
# * Cloud coverage less than 50%
#############################################################

- alias: 'Turn off light when sun rises +1h and no clouds'
  trigger:
    platform: sun
    event: sunrise
    offset: "+01:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.yr_cloudiness
      below: 50
    - condition: state
      entity_id: group.lights_livingroom
      state: 'on'
  action:
    service: 'scene.turn_on'
    entity_id: 'scene.sunrise'

#############################################################
# Sunrise +2 hours
# Conditions:
# * Lights on
#############################################################

- alias: 'Turn off light when sun rises +2h'
  trigger:
    platform: sun
    event: sunrise
    offset: "+02:00:00"
  condition:
    - condition: state
      entity_id: group.lights_livingroom
      state: 'on'
  action:
    service: 'scene.turn_on'
    entity_id: 'scene.sunrise'

