######################################################
# Morning lights
######################################################

- alias: 'Turn on lights in the morning'
  trigger:
    platform: state
    entity_id: 'input_boolean.house_awake'
    from: 'off'
    to: 'on'
  condition:
    - condition: time
      after: '05:00:01'
      before: '12:00:00'
    - condition: sun
      before: sunrise
      before_offset: "+01:00:00"
  action:
    - service: 'scene.turn_on'
      entity_id: 'scene.lights'


- alias: 'House awakens'
  trigger:
    platform: state
    entity_id: binary_sensor.movement_upstairs
    state: 'on'
  condition:
    - condition: time
      after: '05:00:01'
      before: '12:00:00'
    - condition: state
      entity_id: 'input_boolean.sleeping'
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: 'input_boolean.sleeping'
    - service: homeassistant.turn_off
      entity_id: 'input_boolean.house_awake'
    - delay: 00:00:01
      # All this to get a proper timestamp
    - service: homeassistant.turn_on
      entity_id: 'input_boolean.house_awake'
