#############################################################
# Sunrise +1 hour
# Conditions:
# * Not away
# * Cloud coverage less than 70%
#############################################################

- alias: 'Turn on outdoor lights before sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    - service: 'switch.turn_on'
      entity_id: 'switch.shed_switch'

#############################################################
# Sunrise +2 hours
# Conditions:
# * Not away
#############################################################

- alias: 'Turn off outdoor lights after sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: "+01:00:00"
  action:
    service: 'switch.turn_on'
    entity_id: 'switch.shed_switch'

