#####################################################
# Turn off sleeping in the middle of the day
#####################################################

- alias: 'Turn off sleeping at daytime'
  trigger:
    - platform: time
      after: '13:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:  input_boolean.sleeping
    - service: homeassistant.turn_off
      entity_id:  input_boolean.extend_night

#####################################################
# Notification test
#####################################################

#- alias: 'Send notification when sun rises'
#  trigger:
#    - platform: time
#      after: '15:30:00'
#  action:
#    service: notify.pushbullet
#    data:
#      message: 'Work is out!'

#####################################################
# Notification when doors open
#####################################################

- alias: 'Send notification when a door is opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.main_door
      state: 'on'
    - platform: state
      entity_id: binary_sensor.back_door
      state: 'on'
  action:
    service: notify.pushbullet
    data:
      message: 'Door is open!'

