- alias: 'Sleep now button'
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_now
      to: 'on'
  condition:
    condition: or
    conditions:
    - condition: time
      after: '20:00:00'
      before: '23:59:00'
    - condition: time
      after: '00:00:00'
      before: '04:45:00'
  action:
    #- service: script.turn_off_tv
    - service: script.sonos_say
      data:
        sonos_entity: media_player.living_room
        volume: 0.3
        message: 'Good night and sweet dreams. Lights will be out in 5 minutes.'
        delay: '00:00:10'
    - delay: 00:05:00
    - service: 'scene.turn_on'
      entity_id: 'scene.good_night'
    - service: homeassistant.turn_on
      entity_id: 'input_boolean.sleeping'
    - service: homeassistant.turn_off
      entity_id: 'input_boolean.house_asleep'
    - delay: 00:00:01
    - service: homeassistant.turn_on
      entity_id: 'input_boolean.house_asleep'
    - delay: 00:00:02
    - service: homeassistant.turn_off
      entity_id: input_boolean.sleep_now

