- alias: 'Home Assistant status'
  trigger:
    - platform: state
      entity_id: input_boolean.home_status
      from: "off"
      to: "on"
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.living_room
        volume: 0.5
#        message: "This is a simple test"
        message: >
          {% if now().strftime("%H")|int < 12 %}
          Good morning.
          {% elif now().strftime("%H")|int < 18 %}
          Good afternoon.
          {% else %}
          Good evening.
          {% endif %}
          It's currently {{states.sensor.dark_sky_summary.state}} and {{states.sensor.netatmo_outdoor_temperature.state|round}} degrees at home. 
          Today will be {{states.sensor.dark_sky_hourly_summary.state|replace(".", "")}}, with a high of {{states.sensor.dark_sky_daily_high_temperature.state|round}} degrees.
          {% if is_state('sensor.binary_sensor.washmachine', 'on') %}
          By the way, The washing machine is currently running.
          {% endif %}
        delay: '00:00:30'
    - delay: 00:00:10
    - service: homeassistant.turn_off
      entity_id: input_boolean.home_status

