- alias: 'Washing Machine is done'
  trigger:
    platform: state
    entity_id: binary_sensor.washmachine
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 7
      seconds: 0
  action:
    - service: script.telegram
      data:
        message: 'Washing machine is done!'
    - service: script.sonos_say
      data:
        sonos_entity: media_player.living_room
        volume: 0.5
        message: 'Excuse me, but the washing machine just finished its cycle.'
        delay: '00:00:10'

